version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/openfab
    steps:
      - checkout
      - run:
          name: install AWS CLI (first install pip, the Python package manager)
          command: |
            sudo pip install awscli

      - run:
          name: remove .git folder
          command: |
            sudo rm -rf ~/openfab/.git

      - deploy:
          name: deploy to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 sync ~/openfab \
              s3://openfab.be/ --acl public-read --delete
            else
              echo "Not master branch, dry run only"
            fi
